name: Lint code

on:
  push:
    paths:
      - "src/**"
      - "tests/**"

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: poetry run flake8

      - name: Run black
        run: poetry run black --check

      - name: Run isort
        run: poetry run isort --check-only

      - name: Run mypy
        run: poetry run mypy
